/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTaxLossRouteImport } from './routes/_authenticated/tax-loss'
import { Route as AuthenticatedStatementRouteImport } from './routes/_authenticated/statement'
import { Route as AuthenticatedSp500RouteImport } from './routes/_authenticated/sp500'
import { Route as AuthenticatedRebalancingRouteImport } from './routes/_authenticated/rebalancing'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedMappingsRouteImport } from './routes/_authenticated/mappings'
import { Route as AuthenticatedIncomeRouteImport } from './routes/_authenticated/income'
import { Route as AuthenticatedHoldingsRouteImport } from './routes/_authenticated/holdings'
import { Route as AuthenticatedFinancialsRouteImport } from './routes/_authenticated/financials'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTaxLossRoute = AuthenticatedTaxLossRouteImport.update({
  id: '/tax-loss',
  path: '/tax-loss',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatementRoute = AuthenticatedStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSp500Route = AuthenticatedSp500RouteImport.update({
  id: '/sp500',
  path: '/sp500',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRebalancingRoute =
  AuthenticatedRebalancingRouteImport.update({
    id: '/rebalancing',
    path: '/rebalancing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMappingsRoute = AuthenticatedMappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncomeRoute = AuthenticatedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHoldingsRoute = AuthenticatedHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancialsRoute = AuthenticatedFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/holdings': typeof AuthenticatedHoldingsRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/mappings': typeof AuthenticatedMappingsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/rebalancing': typeof AuthenticatedRebalancingRoute
  '/sp500': typeof AuthenticatedSp500Route
  '/statement': typeof AuthenticatedStatementRoute
  '/tax-loss': typeof AuthenticatedTaxLossRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/upload': typeof AuthenticatedUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/holdings': typeof AuthenticatedHoldingsRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/mappings': typeof AuthenticatedMappingsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/rebalancing': typeof AuthenticatedRebalancingRoute
  '/sp500': typeof AuthenticatedSp500Route
  '/statement': typeof AuthenticatedStatementRoute
  '/tax-loss': typeof AuthenticatedTaxLossRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/upload': typeof AuthenticatedUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financials': typeof AuthenticatedFinancialsRoute
  '/_authenticated/holdings': typeof AuthenticatedHoldingsRoute
  '/_authenticated/income': typeof AuthenticatedIncomeRoute
  '/_authenticated/mappings': typeof AuthenticatedMappingsRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/rebalancing': typeof AuthenticatedRebalancingRoute
  '/_authenticated/sp500': typeof AuthenticatedSp500Route
  '/_authenticated/statement': typeof AuthenticatedStatementRoute
  '/_authenticated/tax-loss': typeof AuthenticatedTaxLossRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/financials'
    | '/holdings'
    | '/income'
    | '/mappings'
    | '/performance'
    | '/rebalancing'
    | '/sp500'
    | '/statement'
    | '/tax-loss'
    | '/transactions'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/financials'
    | '/holdings'
    | '/income'
    | '/mappings'
    | '/performance'
    | '/rebalancing'
    | '/sp500'
    | '/statement'
    | '/tax-loss'
    | '/transactions'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/financials'
    | '/_authenticated/holdings'
    | '/_authenticated/income'
    | '/_authenticated/mappings'
    | '/_authenticated/performance'
    | '/_authenticated/rebalancing'
    | '/_authenticated/sp500'
    | '/_authenticated/statement'
    | '/_authenticated/tax-loss'
    | '/_authenticated/transactions'
    | '/_authenticated/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tax-loss': {
      id: '/_authenticated/tax-loss'
      path: '/tax-loss'
      fullPath: '/tax-loss'
      preLoaderRoute: typeof AuthenticatedTaxLossRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statement': {
      id: '/_authenticated/statement'
      path: '/statement'
      fullPath: '/statement'
      preLoaderRoute: typeof AuthenticatedStatementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sp500': {
      id: '/_authenticated/sp500'
      path: '/sp500'
      fullPath: '/sp500'
      preLoaderRoute: typeof AuthenticatedSp500RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rebalancing': {
      id: '/_authenticated/rebalancing'
      path: '/rebalancing'
      fullPath: '/rebalancing'
      preLoaderRoute: typeof AuthenticatedRebalancingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mappings': {
      id: '/_authenticated/mappings'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof AuthenticatedMappingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/income': {
      id: '/_authenticated/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AuthenticatedIncomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/holdings': {
      id: '/_authenticated/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof AuthenticatedHoldingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financials': {
      id: '/_authenticated/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AuthenticatedFinancialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancialsRoute: typeof AuthenticatedFinancialsRoute
  AuthenticatedHoldingsRoute: typeof AuthenticatedHoldingsRoute
  AuthenticatedIncomeRoute: typeof AuthenticatedIncomeRoute
  AuthenticatedMappingsRoute: typeof AuthenticatedMappingsRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedRebalancingRoute: typeof AuthenticatedRebalancingRoute
  AuthenticatedSp500Route: typeof AuthenticatedSp500Route
  AuthenticatedStatementRoute: typeof AuthenticatedStatementRoute
  AuthenticatedTaxLossRoute: typeof AuthenticatedTaxLossRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancialsRoute: AuthenticatedFinancialsRoute,
  AuthenticatedHoldingsRoute: AuthenticatedHoldingsRoute,
  AuthenticatedIncomeRoute: AuthenticatedIncomeRoute,
  AuthenticatedMappingsRoute: AuthenticatedMappingsRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedRebalancingRoute: AuthenticatedRebalancingRoute,
  AuthenticatedSp500Route: AuthenticatedSp500Route,
  AuthenticatedStatementRoute: AuthenticatedStatementRoute,
  AuthenticatedTaxLossRoute: AuthenticatedTaxLossRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
